# Generated by Django 5.2 on 2025-04-13 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seemeApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='dimension_counts',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
